// ============================================================
// fonts.js — friendly font names -> Google Fonts descriptors
// Ported 1:1 from font_table in CustomNameKeychainGenerator_100Fonts.scad
// ============================================================

// [friendlyName, openscadDescriptor] — descriptor uses OpenSCAD's
// "Family:style=Bold" syntax for the handful of fonts where the bold
// variant is what we actually want.
export const FONT_TABLE = [
  ["Anton", "Anton"],
  ["Baloo 2 Bold", "Baloo 2"],
  ["Bree Serif", "Bree Serif"],
  ["Bebas Neue", "Bebas Neue"],
  ["Archivo Black", "Archivo Black"],
  ["Bungee", "Bungee"],
  ["Righteous", "Righteous"],
  ["Bangers", "Bangers"],
  ["Comfortaa Bold", "Comfortaa:style=Bold"],
  ["Poetsen One", "Poetsen One"],
  ["Cinzel Decorative Bold", "Cinzel Decorative:style=Bold"],
  ["Damion", "Damion"],
  ["Caveat Bold", "Caveat:style=Bold"],
  ["Press Start 2P", "Press Start 2P"],
  ["Alfa Slab One", "Alfa Slab One"],
  ["Bagel Fat One", "Bagel Fat One"],
  ["Bakbak One", "Bakbak One"],
  ["Black Ops One", "Black Ops One"],
  ["Boogaloo", "Boogaloo"],
  ["Chewy", "Chewy"],
  ["Chonburi", "Chonburi"],
  ["Coiny", "Coiny"],
  ["Contrail One", "Contrail One"],
  ["Racing Sans One", "Racing Sans One"],
  ["Rammetto One", "Rammetto One"],
  ["Ranchers", "Ranchers"],
  ["Bevan", "Bevan"],
  ["Black Han Sans", "Black Han Sans"],
  ["Bungee Shade", "Bungee Shade"],
  ["Bungee Outline", "Bungee Outline"],
  ["Bungee Inline", "Bungee Inline"],
  ["Carter One", "Carter One"],
  ["Changa One", "Changa One"],
  ["Chango", "Chango"],
  ["Cherry Bomb One", "Cherry Bomb One"],
  ["Concert One", "Concert One"],
  ["Atomic Age", "Atomic Age"],
  ["Audiowide", "Audiowide"],
  ["Aboreto", "Aboreto"],
  ["Crete Round", "Crete Round"],
  ["DM Serif Display", "DM Serif Display"],
  ["Dangrek", "Dangrek"],
  ["Berkshire Swash", "Berkshire Swash"],
  ["Abril Fatface", "Abril Fatface"],
  ["Aldrich", "Aldrich"],
  ["Bowlby One", "Bowlby One"],
  ["Chicle", "Chicle"],
  ["Cherry Cream Soda", "Cherry Cream Soda"],
  ["Baumans", "Baumans"],
  ["ABeeZee", "ABeeZee"],
  ["Titan One", "Titan One"],
  ["Unbounded", "Unbounded"],
  ["Varela Round", "Varela Round"],
  ["Wallpoet", "Wallpoet"],
  ["Yusei Magic", "Yusei Magic"],
  ["Zen Dots", "Zen Dots"],
  ["Young Serif", "Young Serif"],
  ["Vast Shadow", "Vast Shadow"],
  ["Vina Sans", "Vina Sans"],
  ["Zen Maru Gothic", "Zen Maru Gothic"],
  ["Suez One", "Suez One"],
  ["Syncopate", "Syncopate"],
  ["Roboto", "Roboto"],
  ["Roboto Slab", "Roboto Slab"],
  ["Rubik", "Rubik"],
  ["Russo One", "Russo One"],
  ["Seymour One", "Seymour One"],
  ["Sigmar One", "Sigmar One"],
  ["Space Grotesk", "Space Grotesk"],
  ["Stalinist One", "Stalinist One"],
  ["Squada One", "Squada One"],
  ["Silkscreen", "Silkscreen"],
  ["Secular One", "Secular One"],
  ["Rye", "Rye"],
  ["Ruslan Display", "Ruslan Display"],
  ["Sancreek", "Sancreek"],
  ["Shrikhand", "Shrikhand"],
  ["Spicy Rice", "Spicy Rice"],
  ["Special Elite", "Special Elite"],
  ["MuseoModerno", "MuseoModerno"],
  ["Nerko One", "Nerko One"],
  ["New Rocker", "New Rocker"],
  ["Nixie One", "Nixie One"],
  ["New Amsterdam", "New Amsterdam"],
  ["Notable", "Notable"],
  ["Nosifer", "Nosifer"],
  ["Pacifico", "Pacifico"],
  ["Paprika", "Paprika"],
  ["Passero One", "Passero One"],
  ["Patrick Hand", "Patrick Hand"],
  ["Paytone One", "Paytone One"],
  ["Peralta", "Peralta"],
  ["Permanent Marker", "Permanent Marker"],
  ["Pirata One", "Pirata One"],
  ["Playfair Display", "Playfair Display"],
  ["Plaster", "Plaster"],
  ["Oswald", "Oswald"],
  ["Orbitron", "Orbitron"],
  ["Original Surfer", "Original Surfer"],
  ["Oleo Script", "Oleo Script"],

  // ---- +200 more, added later: bold/blocky/rounded/geometric faces
  // chosen for print-friendly thick strokes over fine hairlines.
  // ":style=Bold" is used on normal-weight text families so the
  // heavier, more printable weight renders instead of the thin default.
  ["Fredoka Bold", "Fredoka:style=Bold"],
  ["Quicksand Bold", "Quicksand:style=Bold"],
  ["Nunito Bold", "Nunito:style=Bold"],
  ["Poppins Bold", "Poppins:style=Bold"],
  ["Montserrat Bold", "Montserrat:style=Bold"],
  ["Raleway Bold", "Raleway:style=Bold"],
  ["Karla Bold", "Karla:style=Bold"],
  ["Manrope Bold", "Manrope:style=Bold"],
  ["Sora Bold", "Sora:style=Bold"],
  ["Outfit Bold", "Outfit:style=Bold"],
  ["Plus Jakarta Sans Bold", "Plus Jakarta Sans:style=Bold"],
  ["Lexend Bold", "Lexend:style=Bold"],
  ["Epilogue Bold", "Epilogue:style=Bold"],
  ["Red Hat Display Bold", "Red Hat Display:style=Bold"],
  ["Urbanist Bold", "Urbanist:style=Bold"],
  ["Jost Bold", "Jost:style=Bold"],
  ["DM Sans Bold", "DM Sans:style=Bold"],
  ["Cabin Bold", "Cabin:style=Bold"],
  ["Josefin Sans Bold", "Josefin Sans:style=Bold"],
  ["Work Sans Bold", "Work Sans:style=Bold"],
  ["Exo 2", "Exo 2"],
  ["Rajdhani", "Rajdhani"],
  ["Play", "Play"],
  ["Electrolize", "Electrolize"],
  ["Michroma", "Michroma"],
  ["Chakra Petch", "Chakra Petch"],
  ["Prompt", "Prompt"],
  ["Kanit", "Kanit"],
  ["Iceland", "Iceland"],
  ["Voltaire", "Voltaire"],
  ["VT323", "VT323"],
  ["Major Mono Display", "Major Mono Display"],
  ["Turret Road", "Turret Road"],
  ["Coda", "Coda"],
  ["Faster One", "Faster One"],
  ["Monoton", "Monoton"],
  ["Frijole", "Frijole"],
  ["Fascinate", "Fascinate"],
  ["Geostar", "Geostar"],
  ["Geostar Fill", "Geostar Fill"],
  ["Nova Square", "Nova Square"],
  ["Nova Round", "Nova Round"],
  ["Nova Flat", "Nova Flat"],
  ["Nova Cut", "Nova Cut"],
  ["Nova Mono", "Nova Mono"],
  ["Rubik Mono One", "Rubik Mono One"],
  ["Rubik Bubbles", "Rubik Bubbles"],
  ["Rubik Dirt", "Rubik Dirt"],
  ["Rubik Doodle Shadow", "Rubik Doodle Shadow"],
  ["Rubik Gemstones", "Rubik Gemstones"],
  ["Rubik Iso", "Rubik Iso"],
  ["Rubik Maze", "Rubik Maze"],
  ["Rubik Microbe", "Rubik Microbe"],
  ["Rubik Moonrocks", "Rubik Moonrocks"],
  ["Rubik Puddles", "Rubik Puddles"],
  ["Rubik Storm", "Rubik Storm"],
  ["Rubik Vinyl", "Rubik Vinyl"],
  ["Rubik Wet Paint", "Rubik Wet Paint"],
  ["Rubik Spray Paint", "Rubik Spray Paint"],
  ["Rubik Marker Hatch", "Rubik Marker Hatch"],
  ["Fugaz One", "Fugaz One"],
  ["Graduate", "Graduate"],
  ["Emblema One", "Emblema One"],
  ["Erica One", "Erica One"],
  ["Miltonian", "Miltonian"],
  ["Metal Mania", "Metal Mania"],
  ["Butcherman", "Butcherman"],
  ["Creepster", "Creepster"],
  ["Eater", "Eater"],
  ["Freckle Face", "Freckle Face"],
  ["Griffy", "Griffy"],
  ["Irish Grover", "Irish Grover"],
  ["Jolly Lodger", "Jolly Lodger"],
  ["Lacquer", "Lacquer"],
  ["Londrina Outline", "Londrina Outline"],
  ["Londrina Shadow", "Londrina Shadow"],
  ["Londrina Solid", "Londrina Solid"],
  ["Mystery Quest", "Mystery Quest"],
  ["Snowburst One", "Snowburst One"],
  ["Sonsie One", "Sonsie One"],
  ["Spirax", "Spirax"],
  ["Trade Winds", "Trade Winds"],
  ["Vampiro One", "Vampiro One"],
  ["Kavoon", "Kavoon"],
  ["Kelly Slab", "Kelly Slab"],
  ["Knewave", "Knewave"],
  ["Fontdiner Swanky", "Fontdiner Swanky"],
  ["Gorditas", "Gorditas"],
  ["Gravitas One", "Gravitas One"],
  ["Henny Penny", "Henny Penny"],
  ["Modak", "Modak"],
  ["Mogra", "Mogra"],
  ["Bungee Spice", "Bungee Spice"],
  ["Cabin Sketch", "Cabin Sketch"],
  ["Caesar Dressing", "Caesar Dressing"],
  ["Chelsea Market", "Chelsea Market"],
  ["Corben", "Corben"],
  ["Days One", "Days One"],
  ["Dela Gothic One", "Dela Gothic One"],
  ["DynaPuff", "DynaPuff"],
  ["Ewert", "Ewert"],
  ["Finger Paint", "Finger Paint"],
  ["Flavors", "Flavors"],
  ["Fresca", "Fresca"],
  ["Fruktur", "Fruktur"],
  ["Galada", "Galada"],
  ["Geo", "Geo"],
  ["Goblin One", "Goblin One"],
  ["Lancelot", "Lancelot"],
  ["Load", "Load"],
  ["Macondo", "Macondo"],
  ["Mate SC", "Mate SC"],
  ["Miniver", "Miniver"],
  ["Nova Script", "Nova Script"],
  ["Offside", "Offside"],
  ["Rancho", "Rancho"],
  ["Ribeye", "Ribeye"],
  ["Ribeye Marrow", "Ribeye Marrow"],
  ["Rock 3D", "Rock 3D"],
  ["Sail", "Sail"],
  ["Sedgwick Ave", "Sedgwick Ave"],
  ["Sedgwick Ave Display", "Sedgwick Ave Display"],
  ["Shojumaru", "Shojumaru"],
  ["Sirin Stencil", "Sirin Stencil"],
  ["Skranji", "Skranji"],
  ["Sofia", "Sofia"],
  ["Stardos Stencil", "Stardos Stencil"],
  ["Stint Ultra Condensed", "Stint Ultra Condensed"],
  ["Stint Ultra Expanded", "Stint Ultra Expanded"],
  ["Supermercado One", "Supermercado One"],
  ["Tulpen One", "Tulpen One"],
  ["Bahiana", "Bahiana"],
  ["Bigshot One", "Bigshot One"],
  ["Big Shoulders Display Bold", "Big Shoulders Display:style=Bold"],
  ["Big Shoulders Text Bold", "Big Shoulders Text:style=Bold"],
  ["Big Shoulders Stencil Display", "Big Shoulders Stencil Display"],
  ["Big Shoulders Stencil Text", "Big Shoulders Stencil Text"],
  ["BioRhyme Bold", "BioRhyme:style=Bold"],
  ["BioRhyme Expanded", "BioRhyme Expanded"],
  ["Passion One", "Passion One"],
  ["Fjalla One", "Fjalla One"],
  ["Francois One", "Francois One"],
  ["Julius Sans One", "Julius Sans One"],
  ["Lilita One", "Lilita One"],
  ["Luckiest Guy", "Luckiest Guy"],
  ["Baloo", "Baloo"],
  ["Baloo Bhai 2", "Baloo Bhai 2"],
  ["Baloo Bhaijaan 2", "Baloo Bhaijaan 2"],
  ["Baloo Chettan 2", "Baloo Chettan 2"],
  ["Baloo Da 2", "Baloo Da 2"],
  ["Baloo Paaji 2", "Baloo Paaji 2"],
  ["Baloo Tamma 2", "Baloo Tamma 2"],
  ["Baloo Tammudu 2", "Baloo Tammudu 2"],
  ["Baloo Thambi 2", "Baloo Thambi 2"],
  ["Do Hyeon", "Do Hyeon"],
  ["Jua", "Jua"],
  ["Gugi", "Gugi"],
  ["Stylish", "Stylish"],
  ["Gaegu Bold", "Gaegu:style=Bold"],
  ["Gasoek One", "Gasoek One"],
  ["Kirang Haerang", "Kirang Haerang"],
  ["Single Day", "Single Day"],
  ["Poor Story", "Poor Story"],
  ["East Sea Dokdo", "East Sea Dokdo"],
  ["Yeon Sung", "Yeon Sung"],
  ["Dokdo", "Dokdo"],
  ["Song Myung", "Song Myung"],
  ["IBM Plex Sans Bold", "IBM Plex Sans:style=Bold"],
  ["IBM Plex Mono Bold", "IBM Plex Mono:style=Bold"],
  ["IBM Plex Serif Bold", "IBM Plex Serif:style=Bold"],
  ["Inter Tight Bold", "Inter Tight:style=Bold"],
  ["Red Hat Mono Bold", "Red Hat Mono:style=Bold"],
  ["Athiti Bold", "Athiti:style=Bold"],
  ["Krub Bold", "Krub:style=Bold"],
  ["Mitr Bold", "Mitr:style=Bold"],
  ["Niramit Bold", "Niramit:style=Bold"],
  ["Sarabun Bold", "Sarabun:style=Bold"],
  ["Taviraj Bold", "Taviraj:style=Bold"],
  ["Pridi Bold", "Pridi:style=Bold"],
  ["K2D Bold", "K2D:style=Bold"],
  ["Maitree Bold", "Maitree:style=Bold"],
  ["Trirong Bold", "Trirong:style=Bold"],
  ["Bai Jamjuree Bold", "Bai Jamjuree:style=Bold"],
  ["Fahkwang Bold", "Fahkwang:style=Bold"],
  ["Itim", "Itim"],
  ["Mali Bold", "Mali:style=Bold"],
  ["Sriracha", "Sriracha"],
  ["Srisakdi", "Srisakdi"],
  ["Thasadith Bold", "Thasadith:style=Bold"],
  ["Codystar Bold", "Codystar:style=Bold"],
  ["Diplomata", "Diplomata"],
  ["Grenze Gotisch", "Grenze Gotisch"],
  ["Hanalei Fill", "Hanalei Fill"],
  ["Kumar One", "Kumar One"],
  ["Kumar One Outline", "Kumar One Outline"],
  ["Odor Mean Chey", "Odor Mean Chey"],
  ["Piedra", "Piedra"],
  ["Pangolin", "Pangolin"],
  ["Redressed", "Redressed"],
  ["Snippet", "Snippet"],
];

// Build a Google Fonts CSS2 URL for a given descriptor + the exact
// characters we need. Passing `text=` makes Google return a single,
// small, already-subsetted @font-face (one file, no unicode-range
// juggling) which keeps this simple AND fast.
export function googleFontsCssUrl(descriptor, text) {
  const [familyRaw, styleParam] = descriptor.split(":");
  const family = encodeURIComponent(familyRaw.trim()).replace(/%20/g, "+");
  const wantsBold = !!styleParam && styleParam.includes("style=Bold");
  const familyParam = wantsBold ? `${family}:wght@700` : family;
  const chars = encodeURIComponent(
    Array.from(new Set(Array.from(text || "TEXT"))).join("")
  );
  return `https://fonts.googleapis.com/css2?family=${familyParam}&text=${chars}&display=swap`;
}

export function findDescriptor(friendlyName) {
  const row = FONT_TABLE.find((r) => r[0] === friendlyName);
  return row ? row[1] : FONT_TABLE[0][1];
}

// Available to everyone with no license — the rest of FONT_TABLE
// requires a Personal or Commercial license key to select.
export const FREE_FONT_NAMES = ["Anton", "Baloo 2 Bold", "Bree Serif"];

// Monochrome, vector (NOT color-bitmap) emoji font from Google Fonts —
// this is what makes it possible to run emoji through the exact same
// opentype.js -> outline -> extrude pipeline as regular text.
export const EMOJI_FONT_DESCRIPTOR = "Noto Emoji";

// Sentinel value standing in for the Keychain Factory logo icon (ring +
// tag, no text) inside ICON_PALETTE. It's not a real emoji character —
// geometry.js checks for this exact string and builds a small vector
// shape for it directly instead of going through the emoji-font lookup,
// and main.js checks for it to render the real logo image in the
// picker button instead of plain text.
export const LOGO_ICON_KEY = "__kf_logo__";

// Available to everyone with no license — the rest of ICON_PALETTE
// requires a Personal or Commercial license key to select.
export const FREE_ICONS = ["❤️", "⭐", LOGO_ICON_KEY, "⚓", "🔥"];

// 300 single-codepoint icons (a few include the U+FE0F variation selector,
// which geometry.js strips before rendering — that stray character was the
// cause of the stray "tofu" rectangle appearing after some icons). Deliberately
// avoids flags, skin-tone modifiers, and multi-part ZWJ sequences (couples,
// families, professions), which render unreliably across emoji fonts.
export const ICON_PALETTE = [
  "❤️", "⭐", LOGO_ICON_KEY, "⚓", "🔥", "⚡", "🌙", "☀️", "🍀", "🦋",
  "🐱", "🐶", "🎮", "🎵", "✈️", "🌸", "💀", "👑", "🐝", "🌊",
  "🎯", "🚀", "🏀", "⚽", "🐉", "🦄", "💎", "🎸", "🌵", "🍕",
  "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐸",
  "🐵", "🐔", "🐧", "🐦", "🦉", "🐺", "🐗", "🐴", "🦓", "🦒",
  "🐘", "🐢", "🐍", "🦎", "🐙", "🐬", "🐳", "🐟", "🦈", "🦀",
  "🐌", "🐞", "🦂", "🐊", "🦖", "🌈", "✨", "🌍", "🍄", "🌹",
  "🌻", "🌼", "🌷", "🍁", "🌴", "🌲", "🎋", "♥️", "♦️", "🛡️",
  "🔱", "🔮", "💍", "🔔", "🎁", "🏆", "🥇", "🔑", "⚖️", "🧭",
  "⏰", "💡", "🎪", "🎭", "🎨", "🎲", "🍔", "🍩", "🎂", "🍎",

  // ---- +200 more: broader coverage across animals, food, sports,
  // travel/places, weather, plants, everyday objects, and symbols.
  "🐭", "🐹", "🦔", "🦇", "🦅", "🦆", "🦃", "🐓", "🦚", "🦜",
  "🐿️", "🦡", "🦨", "🦘", "🦙", "🐐", "🐑", "🐄", "🐎", "🐕",
  "🐩", "🐈", "🦥", "🦦", "🦫", "🐁", "🐀", "🦭", "🐡", "🐠",
  "🦞", "🦐", "🦑", "🐚", "🦩", "🦢", "🦟", "🕸️", "🦗", "🐛",
  "🍟", "🌭", "🍿", "🧀", "🥓", "🍳", "🥞", "🧇", "🥐", "🥖",
  "🥨", "🥯", "🍞", "🧈", "🍗", "🍖", "🥩", "🌮", "🥙", "🍝",
  "🍜", "🍲", "🍛", "🍣", "🍱", "🍤", "🍙", "🍘", "🍥", "🥟",
  "🍢", "🍡", "🍧", "🍨", "🍦", "🥧", "🧁", "🍮", "🍭", "🍬",
  "🍫", "🍯", "🍪", "🥛", "🍺", "🍷", "🍹", "🍸", "🍾", "☕",
  "🍵", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🏓", "🏸",
  "🥅", "⛳", "🏹", "🎣", "🥊", "🥋", "🛹", "⛸️", "🥌", "🎿",
  "🏂", "🥈", "🥉", "🎖️", "🏵️", "🎗️", "🚗", "🚕", "🚙", "🚌",
  "🏎️", "🚓", "🚑", "🚒", "🚚", "🚜", "🛵", "🏍️", "🚲", "🛴",
  "🚂", "🚆", "🛸", "🚁", "⛵", "🚤", "🚢", "🗽", "🗼", "🏰",
  "🏯", "🎡", "🎢", "🎠", "⛲", "⛺", "🏖️", "🏜️", "🏝️", "🏔️",
  "⛰️", "🌋", "🗻", "⛅", "⛈️", "❄️", "🌪️", "🌫️", "🌀", "☔",
  "🌱", "🌿", "☘️", "🎍", "🎄", "🌰", "🍃", "🌾", "💐", "🥀",
  "🌺", "⌚", "📱", "💻", "🖥️", "📷", "🔍", "🔦", "🕯️", "💰",
  "🐾", "📦", "✏️", "📐", "✂️", "🔒", "🔨", "⚙️", "🧲", "🔗",
  "🧪", "🔬", "🔭", "💊", "🎈", "🎉", "🎀", "🎫", "🖼️", "🧶",
];
